######################################################################
# Automatically generated by qmake (3.1) Wed Apr 23 02:19:43 2025
######################################################################

TEMPLATE = app
TARGET = test
CONFIG -= qt
CONFIG += console

LIBS += -lgtest

INCLUDEPATH += ../include

win32:INCLUDEPATH += C:/googletest-1.16.0/googletest/include
win32:CONFIG(debug,debug|release):LIBS += -LC:/googletest-1.16.0/build/lib/Debug
win32:CONFIG(release,debug|release):LIBS += -LC:/googletest-1.16.0/build/lib/Release

HEADERS += \
	test.h \
	../include/xstream.h
SOURCES += \
    test1.cpp \
    test2.cpp \
    testmain.cpp
